### PR TITLE
additional changes to eduhelx_chip690_fix branch 

### PR DESCRIPTION
**Pull request by muralikarthikk**

### CODE REVIEW

**Review by pj-linebaugh — APPROVED** [review]
The limits on jupyter-datascience-db and rstudio might need to be increased some.  You should check on what they are in the eduhelx_chip690_fix branch.  These changes will need to be merged into the eduhelx_chip690_fix branch of helx-apps for the changes to show up in the eduhelx-chip690 appstore (after appstore pod restart).

**Comment by muralikarthikk** [comment]
> The limits on jupyter-datascience-db and rstudio might need to be increased some. You should check on what they are in the eduhelx_chip690_fix branch. These changes will need to be merged into the eduhelx_chip690_fix branch of helx-apps for the changes to show up in the eduhelx-chip690 appstore (after appstore pod restart).

Will change the limits for those apps. There was a mention about using new branch "eduhelx_chip690" branch which based off of "eduhelx_chip690_fix"? Is this PR valid? or should i merge to eduhelx_chip690_fix?

**Comment by muralikarthikk** [comment]
What should be the limits for those apps?

**Comment by pj-linebaugh** [comment]
Avoid changing the requests/limits in the "eduhelx_chip690_fix" branch unless you know of a reason to do so.

**Comment by muralikarthikk** [comment]
> Avoid changing the requests/limits in the "eduhelx_chip690_fix" branch unless you know of a reason to do so. And also be sure to check with Isma to see if she wants the changes to be live in the class.

I will keep the resources as is, we can update that later as per the requirement. Isma mentioned about discussing with Ashok and Emily before making this live.

**Pull request closed without merging**
